@accounts = ["Savings", "Checkings", "College"]
@bals = [400.00, 300.00, 200.00]

5.times do |i|
  emailStr = "#{Faker::Science.element}#{i}@mail.com"
  #instead of a concatination (would not run), we had to do an interpolation here, where the #{i} adds an integer to the email address, preventing duplicates that may be generated by the Faker file. 
  user = User.create(
    email: emailStr,
    password: "password",
    first_name: Faker::Dessert.variety,
    last_name: Faker::Emotion.noun
  )
  3.times do 
    Account.create(
      account_name: @accounts.sample,
      balance: @bals.sample,
      user_id: user.id
    )
  end
end

puts "Data seeded"